[book]
title = "The Numra Book"
authors = ["Moussa Leblouba"]
language = "en"
src = "src"
description = "Comprehensive guide to Numra, the numerical methods library for Rust"

[build]
build-dir = "book"
create-missing = true

[output.html]
mathjax-support = true
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/moussaoutlook/numra-rs"
edit-url-template = "https://github.com/moussaoutlook/numra-rs/edit/main/numra-book/{path}"
site-url = "/numra/"
no-section-label = false

[output.pdf]

[output.html.fold]
enable = true
level = 1
