#!/usr/bin/env bash
# ----------------------------------------------------------------------
# mdBook → Starlight migration helper for Numra
#
# What it does:
#   1. Copies markdown files from an existing mdBook source directory
#      into the Starlight content directory.
#   2. Adds frontmatter (title from H1, optional description) to files
#      that don't already have it.
#   3. Strips the H1 (Starlight renders title from frontmatter, not H1).
#   4. Rewrites internal links to remove .md extensions.
#   5. Reports anything it can't migrate cleanly so you can fix manually.
#
# What it does NOT do:
#   - Convert {{#include}}, {{#playground}}, {{#rustdoc_include}}
#     directives. These are flagged for manual conversion to MDX
#     imports.
#   - Move images. Image references are reported; you'll need to copy
#     the image files into book/src/assets/ and update paths.
#   - Generate the sidebar — the autogenerated sidebar in
#     astro.config.mjs picks up the directory structure automatically.
#
# Usage:
#   ./scripts/migrate-mdbook.sh <mdbook-src-dir> <starlight-content-dir>
#
# Example:
#   ./scripts/migrate-mdbook.sh \
#     ../old-book/src \
#     website/book/src/content/docs
#
# Idempotent: running twice on the same input is safe. Files that
# already have frontmatter are not modified again.
# ----------------------------------------------------------------------

set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <mdbook-src-dir> <starlight-content-dir>" >&2
  echo "" >&2
  echo "Example: $0 ../old-book/src website/book/src/content/docs" >&2
  exit 1
fi

MDBOOK_SRC="$1"
STARLIGHT_DST="$2"

if [[ ! -d "$MDBOOK_SRC" ]]; then
  echo "Error: mdBook source directory does not exist: $MDBOOK_SRC" >&2
  exit 1
fi

mkdir -p "$STARLIGHT_DST"

REPORT_FILE="$(mktemp -t numra-migrate.XXXXXX.txt)"
echo "# Numra mdBook → Starlight migration report" > "$REPORT_FILE"
echo "Generated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$REPORT_FILE"
echo "Source: $MDBOOK_SRC" >> "$REPORT_FILE"
echo "Destination: $STARLIGHT_DST" >> "$REPORT_FILE"
echo "" >> "$REPORT_FILE"

# --------------------------------------------------------------- 1. copy
echo "==> Copying markdown files (excluding SUMMARY.md)..."
# rsync preserves directory structure, excludes mdBook-specific files
rsync -a \
  --include='*/' \
  --include='*.md' \
  --exclude='SUMMARY.md' \
  --exclude='*' \
  "$MDBOOK_SRC"/ "$STARLIGHT_DST"/

COUNT_TOTAL=$(find "$STARLIGHT_DST" -name '*.md' -type f | wc -l | tr -d ' ')
echo "    Copied $COUNT_TOTAL markdown files."

# ----------------------------------------------------------- 2-3. frontmatter
echo "==> Adding frontmatter and stripping H1 from files that lack frontmatter..."

COUNT_FRONTMATTER=0
COUNT_SKIPPED=0
COUNT_NO_H1=0

while IFS= read -r -d '' f; do
  # Check if file already starts with frontmatter
  first_line="$(head -n 1 "$f")"
  if [[ "$first_line" == "---" ]]; then
    COUNT_SKIPPED=$((COUNT_SKIPPED + 1))
    continue
  fi

  # Extract first H1 as the title
  title="$(grep -m1 '^# ' "$f" | sed 's/^# //' || true)"

  if [[ -z "$title" ]]; then
    # No H1 — derive title from filename
    fname="$(basename "$f" .md)"
    # Convert kebab-case or snake_case to Title Case
    title="$(echo "$fname" | sed 's/[-_]/ /g' | awk '{for(i=1;i<=NF;i++) $i=toupper(substr($i,1,1)) tolower(substr($i,2))} 1')"
    COUNT_NO_H1=$((COUNT_NO_H1 + 1))
    echo "  - $f: no H1, derived title from filename: $title" >> "$REPORT_FILE"
  fi

  # Escape any double quotes in the title
  title_escaped="${title//\"/\\\"}"

  # Build new file: frontmatter + body (with H1 stripped)
  tmp="$(mktemp)"
  {
    echo "---"
    echo "title: \"$title_escaped\""
    echo "---"
    echo ""
    # Skip the first H1 line (sed removes only the first match)
    sed '0,/^# /{/^# /d;}' "$f"
  } > "$tmp"
  mv "$tmp" "$f"
  COUNT_FRONTMATTER=$((COUNT_FRONTMATTER + 1))
done < <(find "$STARLIGHT_DST" -name '*.md' -type f -print0)

echo "    Added frontmatter to $COUNT_FRONTMATTER files."
echo "    Skipped $COUNT_SKIPPED files (already had frontmatter)."
echo "    $COUNT_NO_H1 files had no H1 (title derived from filename — verify)."

# ---------------------------------------------------------- 4. link rewrite
echo "==> Rewriting internal .md links to extensionless..."
COUNT_LINKS=0
while IFS= read -r -d '' f; do
  # Match markdown links like [text](path/to/file.md) and (path/to/file.md#anchor)
  # Replace .md with nothing while preserving any anchor.
  if grep -qE '\]\([^)]*\.md(#[^)]*)?\)' "$f" 2>/dev/null; then
    sed -i.bak -E 's#\]\(([^)]*)\.md(#[^)]*)?\)#](\1\2)#g' "$f"
    rm -f "${f}.bak"
    COUNT_LINKS=$((COUNT_LINKS + 1))
  fi
done < <(find "$STARLIGHT_DST" -name '*.md' -type f -print0)
echo "    Rewrote links in $COUNT_LINKS files."

# ----------------------------------------------------- 5. report problems
echo "==> Scanning for content that needs manual attention..."

echo "" >> "$REPORT_FILE"
echo "## Files using mdBook directives (need manual MDX conversion)" >> "$REPORT_FILE"
INCLUDES=$(grep -rln '{{#' "$STARLIGHT_DST" 2>/dev/null || true)
if [[ -n "$INCLUDES" ]]; then
  echo "$INCLUDES" | while read -r f; do
    echo "  - $f" >> "$REPORT_FILE"
    grep -nE '\{\{#[a-z_]+' "$f" | head -5 | sed 's/^/      /' >> "$REPORT_FILE"
  done
else
  echo "  (none — no mdBook directives found)" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "## Files referencing images (verify paths after copy)" >> "$REPORT_FILE"
IMAGES=$(grep -rln -E '!\[[^]]*\]\([^)]+\)' "$STARLIGHT_DST" 2>/dev/null || true)
if [[ -n "$IMAGES" ]]; then
  echo "$IMAGES" | while read -r f; do
    echo "  - $f" >> "$REPORT_FILE"
    grep -nE '!\[[^]]*\]\([^)]+\)' "$f" | head -5 | sed 's/^/      /' >> "$REPORT_FILE"
  done
else
  echo "  (none — no image references found)" >> "$REPORT_FILE"
fi

echo "" >> "$REPORT_FILE"
echo "## Files using non-default math delimiters" >> "$REPORT_FILE"
echo "Files using \\\\(...\\\\) or \\\\[...\\\\] LaTeX-style — need conversion to dollar-sign delimiters:" >> "$REPORT_FILE"
LATEX_DELIM=$(grep -rln -E '\\\\\(|\\\\\[' "$STARLIGHT_DST" 2>/dev/null || true)
if [[ -n "$LATEX_DELIM" ]]; then
  echo "$LATEX_DELIM" | sed 's/^/  - /' >> "$REPORT_FILE"
else
  echo "  (none — math uses standard \$ delimiters or no math present)" >> "$REPORT_FILE"
fi

echo ""
echo "==> Migration complete."
echo "    Report: $REPORT_FILE"
echo ""
echo "Next steps:"
echo "  1. Review the report above for files needing manual attention."
echo "  2. Move image files from $MDBOOK_SRC into book/src/assets/."
echo "  3. Update image references in markdown to point to ../assets/."
echo "  4. Convert any {{#include}} blocks to MDX imports."
echo "  5. Run 'pnpm dev' in book/ to verify the site builds."
echo "  6. Test math rendering on a page with formulas."
echo ""

cat "$REPORT_FILE"
