[package]
name = "numra-interp"
description = "Interpolation and splines for Numra"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
numra-core = { workspace = true }

[dev-dependencies]
approx = { workspace = true }
