// @ts-check
import { defineConfig } from 'astro/config';
import starlight from '@astrojs/starlight';
import { starlightKatex } from 'starlight-katex';

/**
 * Numra book — astro.config.mjs (book.numra-rs.org)
 *
 * Starlight 0.38+ on Astro 6.x.
 *
 * IMPORTANT: math rendering uses the `starlight-katex` plugin, NOT raw
 * remark-math + rehype-katex. The plugin handles known CSS conflicts
 * between Starlight's content styles and KaTeX's SVG output (notably
 * the `\sqrt{}` rendering bug). Do not switch to raw remark-math.
 *
 * Search: Pagefind is built into Starlight by default. No integration
 * needed; index is generated automatically at build time.
 *
 * Sidebar: autogenerated from folder structure under src/content/docs/.
 * Folder names map to URL segments. To control ordering within a group,
 * use frontmatter `sidebar.order: <number>` on each page.
 *
 * @see https://starlight.astro.build/reference/configuration/
 */
export default defineConfig({
  site: 'https://book.numra-rs.org',
  // Starlight builds with directory output (`/foo/index.html`), so
  // requests to `/foo` get a 308 to `/foo/` from Cloudflare Pages.
  // Emitting links with trailing slashes avoids that redirect hop on
  // every internal navigation. The marketing site uses `'never'`
  // because its content is built with `format: 'file'` (single-file
  // pages) — that mismatch is not relevant here.
  trailingSlash: 'always',

  integrations: [
    starlight({
      title: 'Numra',
      description: 'Composable numerical methods for Rust.',

      // Starlight 0.33+ requires an array of link items rather than the
      // pre-0.33 object form documented in the original bundle.
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/moussaoutlook/numra-rs',
        },
      ],

      logo: {
        light: './src/assets/numra_logo_no_BG.svg',
        dark: './src/assets/numra_logo_white_BG.svg',
        replacesTitle: false,
      },

      favicon: '/favicon.svg',

      editLink: {
        baseUrl: 'https://github.com/moussaoutlook/numra-rs/edit/main/website/book/',
      },

      lastUpdated: true,

      customCss: [
        // Order matters: tokens first, then book-specific overrides
        // that reference those tokens.
        './src/styles/tokens.css',
        './src/styles/book-overrides.css',
      ],

      plugins: [
        // KaTeX: handles all the Starlight-aware configuration internally.
        starlightKatex(),
      ],

      // Starlight emits Pagefind output automatically. No config needed
      // unless we want to tune ranking — leave default until search
      // quality complaints appear.

      // Sidebar mirrors numra-book/src/SUMMARY.md exactly. Autogenerate
      // would order alphabetically by filename; SUMMARY orders by
      // pedagogical flow, which is the right one for the reader.
      // Explicit `items:` lists keep the two in sync — when SUMMARY
      // changes, this config must change with it.
      sidebar: [
        {
          label: 'Getting Started',
          items: [
            { label: 'What is Numra?', slug: 'ch01-introduction/what-is-numra' },
            { label: 'Installation', slug: 'ch01-introduction/installation' },
            { label: 'Quick Start', slug: 'ch01-introduction/quick-start' },
            { label: 'Architecture Overview', slug: 'ch01-introduction/architecture-overview' },
          ],
        },
        {
          label: 'Ordinary Differential Equations',
          items: [
            { label: 'Solving ODEs', slug: 'ch02-solving-odes/your-first-ode' },
            { label: 'Solver Options & Configuration', slug: 'ch02-solving-odes/solver-options' },
            { label: 'Explicit Methods', slug: 'ch02-solving-odes/explicit-methods' },
            { label: 'Implicit Methods', slug: 'ch02-solving-odes/implicit-methods' },
            { label: 'Automatic Solver Selection', slug: 'ch02-solving-odes/automatic-selection' },
            { label: 'Dense Output & Interpolation', slug: 'ch02-solving-odes/dense-output' },
            { label: 'Event Detection', slug: 'ch02-solving-odes/event-detection' },
            { label: 'Solver Comparison', slug: 'ch02-solving-odes/solver-comparison' },
            { label: 'Classic Problems', slug: 'ch02-solving-odes/classic-problems' },
            { label: 'Stiff Systems', slug: 'ch03-stiff-systems/what-is-stiffness' },
            { label: 'Detecting Stiffness', slug: 'ch03-stiff-systems/detecting-stiffness' },
            { label: 'Choosing a Stiff Solver', slug: 'ch03-stiff-systems/choosing-a-stiff-solver' },
            { label: 'Differential-Algebraic Equations', slug: 'ch03-stiff-systems/dae-systems' },
            { label: 'Index Reduction', slug: 'ch03-stiff-systems/index-reduction' },
            { label: 'Stiff Solver Comparison', slug: 'ch03-stiff-systems/stiff-comparison' },
          ],
        },
        {
          label: 'Beyond ODEs',
          items: [
            { label: 'Stochastic Differential Equations', slug: 'ch04-beyond-odes/stochastic-des' },
            { label: 'Delay Differential Equations', slug: 'ch04-beyond-odes/delay-des' },
            { label: 'Fractional Differential Equations', slug: 'ch04-beyond-odes/fractional-des' },
            { label: 'Integro-Differential Equations', slug: 'ch04-beyond-odes/integro-des' },
            { label: 'Partial Differential Equations', slug: 'ch04-beyond-odes/partial-des' },
            { label: 'Stochastic PDEs', slug: 'ch04-beyond-odes/stochastic-pdes' },
            { label: 'DE Type Comparison', slug: 'ch04-beyond-odes/de-type-comparison' },
          ],
        },
        {
          label: 'Optimization',
          items: [
            { label: 'Unconstrained Optimization', slug: 'ch05-optimization/unconstrained' },
            { label: 'Constrained Optimization', slug: 'ch05-optimization/constrained' },
            { label: 'Nonlinear Least Squares', slug: 'ch05-optimization/least-squares' },
            { label: 'Linear & Quadratic Programming', slug: 'ch05-optimization/linear-programming' },
            { label: 'Global Optimization', slug: 'ch05-optimization/global-optimization' },
            { label: 'Multi-Objective Optimization', slug: 'ch05-optimization/multi-objective' },
            { label: 'Robust & Stochastic Optimization', slug: 'ch05-optimization/robust-stochastic' },
            { label: 'Optimizer Comparison', slug: 'ch05-optimization/optimizer-comparison' },
          ],
        },
        {
          label: 'Linear Algebra',
          items: [
            { label: 'Matrices & Vectors', slug: 'ch06-linear-algebra/matrices-and-vectors' },
            { label: 'Matrix Factorizations', slug: 'ch06-linear-algebra/factorizations' },
            { label: 'Eigenvalue Problems', slug: 'ch06-linear-algebra/eigenproblems' },
            { label: 'Sparse Matrices', slug: 'ch06-linear-algebra/sparse-matrices' },
            { label: 'Iterative Solvers', slug: 'ch06-linear-algebra/iterative-solvers' },
          ],
        },
        {
          label: 'Calculus & Analysis',
          items: [
            { label: 'Numerical Integration', slug: 'ch07-calculus-and-analysis/numerical-integration' },
            { label: 'Interpolation', slug: 'ch07-calculus-and-analysis/interpolation' },
            { label: 'Automatic Differentiation', slug: 'ch07-calculus-and-analysis/automatic-differentiation' },
            { label: 'Special Functions', slug: 'ch07-calculus-and-analysis/special-functions' },
            { label: 'Curve Fitting', slug: 'ch07-calculus-and-analysis/curve-fitting' },
          ],
        },
        {
          label: 'Signal Processing',
          items: [
            { label: 'FFT & Spectral Analysis', slug: 'ch08-signal-processing/fft-and-spectral' },
            { label: 'Filter Design', slug: 'ch08-signal-processing/filter-design' },
            { label: 'Filtering Signals', slug: 'ch08-signal-processing/filtering-signals' },
            { label: 'Hilbert Transform & Envelope', slug: 'ch08-signal-processing/hilbert-transform' },
            { label: 'Resampling & Peak Detection', slug: 'ch08-signal-processing/resampling-peaks' },
          ],
        },
        {
          label: 'Statistics',
          items: [
            { label: 'Descriptive Statistics', slug: 'ch09-statistics/descriptive-stats' },
            { label: 'Probability Distributions', slug: 'ch09-statistics/distributions' },
            { label: 'Hypothesis Testing', slug: 'ch09-statistics/hypothesis-testing' },
            { label: 'Regression', slug: 'ch09-statistics/regression' },
            { label: 'Correlation', slug: 'ch09-statistics/correlation' },
          ],
        },
        {
          label: 'Optimal Control',
          items: [
            { label: 'Shooting Methods', slug: 'ch10-optimal-control/shooting-methods' },
            { label: 'Collocation', slug: 'ch10-optimal-control/collocation' },
            { label: 'Adjoint Methods', slug: 'ch10-optimal-control/adjoint-methods' },
            { label: 'Parameter Estimation', slug: 'ch10-optimal-control/parameter-estimation' },
          ],
        },
        {
          label: 'Uncertainty & Sensitivity',
          items: [
            { label: 'Error Propagation', slug: 'ch11-uncertainty/error-propagation' },
            { label: 'Sensitivity Analysis', slug: 'ch11-uncertainty/sensitivity-analysis' },
            { label: 'Interval Arithmetic', slug: 'ch11-uncertainty/interval-arithmetic' },
            { label: 'Monte Carlo with ODEs', slug: 'ch11-uncertainty/monte-carlo-odes' },
          ],
        },
        {
          label: 'Advanced Topics',
          items: [
            { label: 'Composing Solvers', slug: 'ch12-advanced-topics/composing-solvers' },
            { label: 'Performance Tuning', slug: 'ch12-advanced-topics/performance-tuning' },
            { label: 'no_std Usage', slug: 'ch12-advanced-topics/no-std-usage' },
            { label: 'Extending Numra', slug: 'ch12-advanced-topics/extending-numra' },
          ],
        },
        {
          label: 'Appendix',
          items: [
            { label: 'Solver Reference Table', slug: 'appendix/solver-reference' },
            { label: 'Method Cards', slug: 'appendix/method-cards' },
            { label: 'Butcher Tableaux', slug: 'appendix/butcher-tableaux' },
            { label: 'Algorithm References', slug: 'appendix/algorithm-references' },
          ],
        },
      ],

      // Code block configuration via Expressive Code (Starlight default).
      expressiveCode: {
        themes: ['github-light', 'github-dark-dimmed'],
        styleOverrides: {
          borderRadius: 'var(--radius-md, 8px)',
          codeFontFamily: 'var(--font-mono)',
        },
      },

      // Components users can hook into. Leave empty until needed; each
      // override means owning a copy of Starlight internals.
      components: {
        // SocialIcons: './src/components/SocialIcons.astro',
      },
    }),
  ],

  // CSP is handled exclusively by Cloudflare Pages headers — see
  // public/_headers. The experimental security.csp meta-tag emitter
  // is intentionally not used: KaTeX emits per-glyph inline
  // `style="height:..."` attributes that no hash can cover, and
  // Pagefind's search UI uses inline styles for the dropdown chrome.
});
